- set_fact:
    loopback_ip: "{{ interfaces[ansible_hostname].loopback }}"
    bridges: "{{ interfaces[ansible_hostname].bridges }}"

- name: configure loopback interface
  cl_interface:
    name: 'lo'
    addr_method: 'loopback'
    ipv4: '{{ loopback_ip }}/32'
  notify: reload networking
  when: loopback_ip is defined
