- name: configure MOTD
  template: src=motd.j2 dest=/etc/motd

- name: License switch
  cl_license: >
    src="http://{{ cl_license_server }}/{{ ansible_hostname }}.lic"
  notify:
    - restart switchd

- name: configure ptmd topology.dot
  copy: src=topology.dot dest=/etc/ptm.d/topology.dot
  notify:
    - restart ptmd

- name: disable arp filter
  sysctl: name=net.ipv4.conf.all.arp_filter value=0 state=present reload=yes
